version: '3.8'

services:
  dialer_redis:
    image: redis:alpine
    container_name: dialer_redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6382:6379"
    networks:
      - omnichat_network

  dialer:
    image: node:20-slim
    container_name: omnichat_dialer
    restart: always
    working_dir: /app
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC@db:5432/omnichat_db?schema=public
      - REDIS_HOST=dialer_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - LIVEKIT_URL=http://172.18.0.1:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devkeysecret32characterslongpass123
      - VITALPBX_API_URL=http://192.168.1.100/api/v2
      - VITALPBX_API_KEY=api_key_here
      - VITALPBX_TRUNK=Local/sip:SHAMPATEL
      - VITALPBX_CONTEXT=cos-all
      - FORCE_RECREATE=1
    command: sh -c "apt-get update -y && apt-get install -y openssl && mkdir -p node_modules && find node_modules -mindepth 1 -delete && npm install && npx prisma generate && npm start"
    ports:
      - "3001:3001"
    volumes:
      - /home/marcio/ominichat/dialer:/app
      - /app/node_modules
    networks:
      - omnichat_network
    depends_on:
      - dialer_redis

networks:
  omnichat_network:
    external: true
    name: omnichat_network
