services:
  asterisk:
    image: andrius/asterisk:20
    container_name: omni-asterisk
    restart: always
    network_mode: host
    volumes:
      - /opt/ominichat/asterisk/conf:/etc/asterisk
      - /opt/ominichat/asterisk/sounds/custom:/var/lib/asterisk/sounds/custom
      - /opt/ominichat/asterisk/agi-bin:/var/lib/asterisk/agi-bin
      - /opt/ominichat/asterisk/monitor:/var/spool/asterisk/monitor

  pbx_api:
    image: ominichat-pbx_api:latest
    container_name: omni-pbx-api
    pull_policy: never
    restart: always
    network_mode: host
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9445"]
    volumes:
      - /opt/ominichat/asterisk/conf:/etc/asterisk
      - /opt/ominichat/asterisk/sounds/custom:/var/lib/asterisk/sounds/custom
      - /opt/ominichat/asterisk/agi-bin:/var/lib/asterisk/agi-bin
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PBX_API_HOST=0.0.0.0
      - PBX_API_PORT=9445
      - PBX_API_ADMIN_USER=admin
      - PBX_API_ADMIN_PASSWORD_HASH=$$2b$$12$$K8aU.CgqLspxNcrZ4s7qE.9zN0iZkFm2JzU5u9y1FvC4m7jJ5uG.a
      - PBX_API_JWT_SECRET=c79f94eb9a694b7e891c338ad7ff6538b71d9d95f87e5a01bcde
      - DATABASE_URL_DIALER=postgresql://postgres:ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC@127.0.0.1:5896/dialer?sslmode=disable
      - DATABASE_URL_CORE=postgresql://postgres:ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC@127.0.0.1:5896/omnichat_db?sslmode=disable
      - ASTERISK_AMI_HOST=127.0.0.1
      - ASTERISK_AMI_PORT=5038
      - ASTERISK_AMI_USER=omnichat_ami
      - ASTERISK_AMI_PASS=omnichat@ami2026!
      - ASTERISK_CONF_DIR=/etc/asterisk
      - ASTERISK_SOUNDS_DIR=/var/lib/asterisk/sounds
      - VOSK_HOST=127.0.0.1
      - VOSK_PORT=2700
      - OMNICHAT_CORE_URL=http://127.0.0.1:3000
      - DIALER_SERVICE_URL=http://127.0.0.1:3001
      - LIVEKIT_URL=http://127.0.0.1:7880
      - LIVEKIT_API_KEY=omnichat_livekit_key
      - LIVEKIT_API_SECRET=OmniChat_LiveKit_Secret_Key_2026_SecurePass!987
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6381
      - REDIS_PASSWORD=ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC
    depends_on:
      - asterisk

  dialer:
    image: ghcr.io/marcio-rgb/omni-dialer:latest
    container_name: omni-dialer
    restart: always
    network_mode: host
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC@127.0.0.1:5896/omnichat_db?schema=public
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6381
      - REDIS_PASSWORD=ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC
      - ASTERISK_AMI_HOST=127.0.0.1
      - ASTERISK_AMI_PORT=5038
      - ASTERISK_AMI_USER=omnichat_ami
      - ASTERISK_AMI_PASSWORD=omnichat@ami2026!
      - OMNICHAT_CORE_URL=http://127.0.0.1:3000
      - PBX_API_URL=http://127.0.0.1:9445
      - LIVEKIT_URL=http://127.0.0.1:7880
      - LIVEKIT_API_KEY=omnichat_livekit_key
      - LIVEKIT_API_SECRET=OmniChat_LiveKit_Secret_Key_2026_SecurePass!987
      - LIVEKIT_SIP_HOST=127.0.0.1:5060
    depends_on:
      - pbx_api
