version: '3.8'

services:
  dialer:
    image: ghcr.io/marcio-rgb/omni-dialer:latest
    container_name: omnichat_dialer
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:ojr6DNM25InIg3qoYI4nbUL5Cx04iCiCn1122@${DB_HOST:-postgres}:5432/omnichat_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ojr6DNM25InIg3qoYI4nbUL5Cx04iCiC
      - LIVEKIT_URL=http://${LIVEKIT_HOST:-livekit}:7880
      - LIVEKIT_API_KEY=omnichat_livekit_key
      - LIVEKIT_API_SECRET=OmniChat_LiveKit_Secret_Key_2026_SecurePass!987
      - LIVEKIT_SIP_HOST=live.creditobr.org:5060
      - VITALPBX_API_URL=https://pbx.creditobr.com.br/api/v2
      - VITALPBX_API_KEY=8302cc7693df6b3795f01ad15d616e11
      - VITALPBX_TRUNK=Local/sip:SHAMPATEL
      - VITALPBX_CONTEXT=cos-all
      - AMI_HOST=pbx.creditobr.com.br
      - AMI_PORT=5038
      - AMI_USER=Omnichat
      - AMI_SECRET=ypnqYP7EHNtYFkqww23243rwew423
      - DIALER_OMNICHAT_SERVER_URL=http://server:3000
      - UPDATE_TIMESTAMP=1784690705
    ports:
      - "3001:3001"
    networks:
      - minha_rede
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=minha_rede"
        - "traefik.http.routers.omnichat-dialer.rule=Host(`api-omnichat.creditobr.org`) && PathPrefix(`/api/v1/calls/ws`)"
        - "traefik.http.routers.omnichat-dialer.entrypoints=websecure"
        - "traefik.http.routers.omnichat-dialer.tls=true"
        - "traefik.http.routers.omnichat-dialer.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.omnichat-dialer.loadbalancer.server.port=3001"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  minha_rede:
    external: true
    name: ${DOCKER_NETWORK_NAME:-minha_rede}
